from __future__ import annotations
import csv
import hashlib
import json
import math
from pathlib import Path

MODULES = ("archive_settlement", "archive_challenge_rewards", "archive_social_rewards",
           "archive_daily_rewards", "archive_online_rewards", "archive_endless_config", "archive_building_rewards", "lottery_http_settlement")

def read_csv(path):
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    header = next(csv.reader([lines[0]]))
    type_line = next((x for x in lines if x.startswith("#types:")), None)
    if type_line is None: raise ValueError(f"csv_types_missing:{path.name}")
    types = type_line[7:].split(",")
    if len(header) != len(types):
        raise ValueError(f"csv_types_mismatch:{path.name}")
    rows, seen = [], set()
    for raw in csv.DictReader(x for x in lines if not x.startswith("#")):
        row = {}
        for key, kind in zip(header, types):
            value = (raw[key] or "").strip()
            if not value:
                continue
            if kind == "number":
                value = float(value)
                if not math.isfinite(value): raise ValueError("csv_nonfinite")
                if value.is_integer(): value = int(value)
            elif kind == "boolean":
                if value.lower() not in {"1","0","true","false","yes","no","on","off"}: raise ValueError("csv_boolean")
                value = value.lower() in {"1","true","yes","on"}
            elif kind == "list": value = [v.strip() for v in value.split("|" if "|" in value else ",") if v.strip()]
            row[key] = value
        identity = row[header[0]]
        if identity in seen: raise ValueError(f"csv_duplicate:{path.name}:{identity}")
        seen.add(identity); rows.append(row)
    return {"key": header[0], "rows": rows}

def build(root: Path):
    # Presentation-only sheets use composite keys and are not settlement rules.
    presentation = {"archive_icon_presentation", "archive_item_icons", "archive_navigation_icons"}
    files = sorted(p for p in (root / "data/csv/存档系统").glob("*.csv") if p.stem not in presentation)
    files += sorted((root / "data/csv/抽奖系统").glob("*.csv"))
    files += [root / "data/csv/玩家档案系统" / (n+".csv") for n in ("player_gameplay_stats","map_level_effect_rules")]
    sources = {"systems/"+n+".lua": (root/"scripts/vscripts/systems"/(n+".lua")).read_text(encoding="utf-8-sig") for n in MODULES}
    for name in ("lottery_config", "content_id_aliases"):
        sources["config/"+name+".lua"] = (root/"scripts/vscripts/config"/(name+".lua")).read_text(encoding="utf-8-sig")
    for name in ("json_encoder","json_decoder"):
        sources["core/"+name+".lua"] = (root/"scripts/vscripts/core"/(name+".lua")).read_text(encoding="utf-8-sig")
    sources["worker.lua"] = (root/"server/archive_backend/worker.lua").read_text(encoding="utf-8-sig")
    configs = {p.stem: read_csv(p) for p in files}
    csv_hashes = {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes().replace(b"\r\n",b"\n")).hexdigest() for p in files}
    data = {"protocol":1,"configs":configs,"sources":sources,"csv_hashes":csv_hashes}
    raw = json.dumps(data,ensure_ascii=False,sort_keys=True,separators=(",",":"),allow_nan=False).encode()
    digest = hashlib.sha256(raw).hexdigest()
    directory = root / "server/bundles" / digest
    directory.mkdir(parents=True,exist_ok=True)
    for path,text in sources.items():
        output=directory/path;output.parent.mkdir(parents=True,exist_ok=True);output.write_text(text,encoding="utf-8",newline="\n")
    (directory/"bundle.json").write_bytes(raw)
    (root/"server/bundles/current.json").write_text(json.dumps({"hash":digest,"protocol":1}),encoding="utf-8")
    (root/"scripts/vscripts/config/generated/archive_http_bundle.lua").write_text(
        '-- AUTO-GENERATED by tools/build_archive_server_bundle.py\nreturn { protocol = 1, hash = "'+digest+'" }\n',encoding="utf-8")
    return digest

class Bundle:
    def __init__(self, directory: Path):
        self.directory = directory.resolve()
        raw = (self.directory/"bundle.json").read_bytes()
        self.hash = hashlib.sha256(raw).hexdigest()
        if self.hash != self.directory.name: raise ValueError("bundle_hash_mismatch")
        data=json.loads(raw);self.configs=data["configs"]
        for path,source in data["sources"].items():
            if (self.directory/path).read_text(encoding="utf-8")!=source: raise ValueError("bundle_source_mismatch")
        self.tables={name:{row[cfg["key"]]:row for row in cfg["rows"]} for name,cfg in self.configs.items()}
