-- Generated from player_gameplay_stats.csv; existing player values are preserved.
begin;
alter table public.player_gameplay_stats add column if not exists "initial_wood" bigint not null default 10;
alter table public.player_gameplay_stats alter column "initial_wood" set default 10;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_initial_wood_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_initial_wood_check" check ("initial_wood"::text not in ('NaN','Infinity','-Infinity') and "initial_wood" >= 0 and "initial_wood"=trunc("initial_wood"));
alter table public.player_gameplay_stats add column if not exists "initial_gold" bigint not null default 0;
alter table public.player_gameplay_stats alter column "initial_gold" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_initial_gold_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_initial_gold_check" check ("initial_gold"::text not in ('NaN','Infinity','-Infinity') and "initial_gold" >= 0 and "initial_gold"=trunc("initial_gold"));
alter table public.player_gameplay_stats add column if not exists "hero_initial_gold" bigint not null default 0;
alter table public.player_gameplay_stats alter column "hero_initial_gold" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_initial_gold_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_initial_gold_check" check ("hero_initial_gold"::text not in ('NaN','Infinity','-Infinity') and "hero_initial_gold" >= 0 and "hero_initial_gold"=trunc("hero_initial_gold"));
alter table public.player_gameplay_stats add column if not exists "health_regen_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "health_regen_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_health_regen_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_health_regen_per_second_check" check ("health_regen_per_second"::text not in ('NaN','Infinity','-Infinity') and "health_regen_per_second" >= 0 and "health_regen_per_second" <= 10000);
alter table public.player_gameplay_stats add column if not exists "wood_per_second" numeric not null default 1;
alter table public.player_gameplay_stats alter column "wood_per_second" set default 1;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wood_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wood_per_second_check" check ("wood_per_second"::text not in ('NaN','Infinity','-Infinity') and "wood_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_attack_efficiency" bigint not null default 13;
alter table public.player_gameplay_stats alter column "lumberjack_attack_efficiency" set default 13;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_attack_efficiency_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_attack_efficiency_check" check ("lumberjack_attack_efficiency"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_attack_efficiency" >= 0 and "lumberjack_attack_efficiency"=trunc("lumberjack_attack_efficiency"));
alter table public.player_gameplay_stats add column if not exists "gold_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_per_second_check" check ("gold_per_second"::text not in ('NaN','Infinity','-Infinity') and "gold_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "gold_mine_efficiency_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_efficiency_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_efficiency_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_efficiency_pct_check" check ("gold_mine_efficiency_pct"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_efficiency_pct" >= 0 and "gold_mine_efficiency_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "initial_population_cap" bigint not null default 0;
alter table public.player_gameplay_stats alter column "initial_population_cap" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_initial_population_cap_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_initial_population_cap_check" check ("initial_population_cap"::text not in ('NaN','Infinity','-Infinity') and "initial_population_cap" >= 0 and "initial_population_cap"=trunc("initial_population_cap"));
alter table public.player_gameplay_stats add column if not exists "starjoy_points" bigint not null default 0;
alter table public.player_gameplay_stats alter column "starjoy_points" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_starjoy_points_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_starjoy_points_check" check ("starjoy_points"::text not in ('NaN','Infinity','-Infinity') and "starjoy_points" >= 0 and "starjoy_points"=trunc("starjoy_points"));
alter table public.player_gameplay_stats add column if not exists "map_level" bigint not null default 0;
alter table public.player_gameplay_stats alter column "map_level" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_map_level_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_map_level_check" check ("map_level"::text not in ('NaN','Infinity','-Infinity') and "map_level" >= 0 and "map_level"=trunc("map_level"));
alter table public.player_gameplay_stats add column if not exists "hero_initial_attack" bigint not null default 100;
alter table public.player_gameplay_stats alter column "hero_initial_attack" set default 100;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_initial_attack_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_initial_attack_check" check ("hero_initial_attack"::text not in ('NaN','Infinity','-Infinity') and "hero_initial_attack" >= 0 and "hero_initial_attack"=trunc("hero_initial_attack"));
alter table public.player_gameplay_stats add column if not exists "hero_damage_attack_growth" numeric not null default 1;
alter table public.player_gameplay_stats alter column "hero_damage_attack_growth" set default 1;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_attack_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_attack_growth_check" check ("hero_damage_attack_growth"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_attack_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_basic_attack_growth" numeric not null default 1;
alter table public.player_gameplay_stats alter column "hero_basic_attack_growth" set default 1;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_basic_attack_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_basic_attack_growth_check" check ("hero_basic_attack_growth"::text not in ('NaN','Infinity','-Infinity') and "hero_basic_attack_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_final_damage_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_final_damage_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_final_damage_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_final_damage_bonus_pct_check" check ("hero_final_damage_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_final_damage_bonus_pct" >= 0 and "hero_final_damage_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_armor_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_armor_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_armor_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_armor_reduction_check" check ("hero_attack_armor_reduction"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_armor_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attribute_growth" numeric not null default 1;
alter table public.player_gameplay_stats alter column "hero_attribute_growth" set default 1;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attribute_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attribute_growth_check" check ("hero_attribute_growth"::text not in ('NaN','Infinity','-Infinity') and "hero_attribute_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attributes_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attributes_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attributes_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attributes_per_second_check" check ("hero_attributes_per_second"::text not in ('NaN','Infinity','-Infinity') and "hero_attributes_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_critical_damage_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_critical_damage_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_critical_damage_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_critical_damage_bonus_pct_check" check ("hero_critical_damage_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_critical_damage_bonus_pct" >= 0 and "hero_critical_damage_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_bonus_pct_check" check ("hero_attack_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_bonus_pct" >= 0 and "hero_attack_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_health_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_health_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_health_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_health_bonus_pct_check" check ("hero_health_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_health_bonus_pct" >= 0 and "hero_health_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_armor_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_armor_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_armor_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_armor_bonus_pct_check" check ("hero_armor_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_armor_bonus_pct" >= 0 and "hero_armor_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_damage_reduction_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_damage_reduction_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_reduction_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_reduction_pct_check" check ("hero_damage_reduction_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_reduction_pct" >= 0 and "hero_damage_reduction_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "tower_attack_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_bonus_pct_check" check ("tower_attack_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_bonus_pct" >= 0 and "tower_attack_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "tower_attack_speed_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_speed_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_speed_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_speed_bonus_pct_check" check ("tower_attack_speed_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_speed_bonus_pct" >= 0 and "tower_attack_speed_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "tower_attack_armor_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_armor_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_armor_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_armor_reduction_check" check ("tower_attack_armor_reduction"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_armor_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_critical_chance_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_critical_chance_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_critical_chance_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_critical_chance_pct_check" check ("tower_critical_chance_pct"::text not in ('NaN','Infinity','-Infinity') and "tower_critical_chance_pct" >= 0 and "tower_critical_chance_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "tower_attack_interval" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_interval" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_interval_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_interval_check" check ("tower_attack_interval"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_interval" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_final_damage_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_final_damage_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_final_damage_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_final_damage_bonus_pct_check" check ("tower_final_damage_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "tower_final_damage_bonus_pct" >= 0 and "tower_final_damage_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "tower_attack_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_per_second_check" check ("tower_attack_per_second"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "wall_damage_block" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_damage_block" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_damage_block_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_damage_block_check" check ("wall_damage_block"::text not in ('NaN','Infinity','-Infinity') and "wall_damage_block" >= 0);
alter table public.player_gameplay_stats add column if not exists "wall_damage_reduction_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_damage_reduction_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_damage_reduction_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_damage_reduction_pct_check" check ("wall_damage_reduction_pct"::text not in ('NaN','Infinity','-Infinity') and "wall_damage_reduction_pct" >= 0 and "wall_damage_reduction_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "wall_armor_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_armor_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_armor_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_armor_bonus_pct_check" check ("wall_armor_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "wall_armor_bonus_pct" >= 0 and "wall_armor_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "wall_health_regen_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_health_regen_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_health_regen_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_health_regen_per_second_check" check ("wall_health_regen_per_second"::text not in ('NaN','Infinity','-Infinity') and "wall_health_regen_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "wall_initial_health" bigint not null default 1000;
alter table public.player_gameplay_stats alter column "wall_initial_health" set default 1000;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_initial_health_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_initial_health_check" check ("wall_initial_health"::text not in ('NaN','Infinity','-Infinity') and "wall_initial_health" >= 0 and "wall_initial_health"=trunc("wall_initial_health"));
alter table public.player_gameplay_stats add column if not exists "wall_armor" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_armor" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_armor_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_armor_check" check ("wall_armor"::text not in ('NaN','Infinity','-Infinity') and "wall_armor" >= 0);
alter table public.player_gameplay_stats add column if not exists "wall_health_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_health_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_health_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_health_bonus_pct_check" check ("wall_health_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "wall_health_bonus_pct" >= 0 and "wall_health_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "wall_health_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_health_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_health_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_health_per_second_check" check ("wall_health_per_second"::text not in ('NaN','Infinity','-Infinity') and "wall_health_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_attack_growth" numeric not null default 1;
alter table public.player_gameplay_stats alter column "lumberjack_attack_growth" set default 1;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_attack_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_attack_growth_check" check ("lumberjack_attack_growth"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_attack_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_attack_speed_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_attack_speed_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_attack_speed_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_attack_speed_bonus_pct_check" check ("lumberjack_attack_speed_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_attack_speed_bonus_pct" >= 0 and "lumberjack_attack_speed_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "online_seconds_total" bigint not null default 0;
alter table public.player_gameplay_stats alter column "online_seconds_total" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_online_seconds_total_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_online_seconds_total_check" check ("online_seconds_total"::text not in ('NaN','Infinity','-Infinity') and "online_seconds_total" >= 0 and "online_seconds_total"=trunc("online_seconds_total"));
alter table public.player_gameplay_stats add column if not exists "hero_initial_attributes" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_initial_attributes" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_initial_attributes_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_initial_attributes_check" check ("hero_initial_attributes"::text not in ('NaN','Infinity','-Infinity') and "hero_initial_attributes" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attributes_per_level" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attributes_per_level" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attributes_per_level_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attributes_per_level_check" check ("hero_attributes_per_level"::text not in ('NaN','Infinity','-Infinity') and "hero_attributes_per_level" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attribute_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attribute_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attribute_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attribute_bonus_pct_check" check ("hero_attribute_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_attribute_bonus_pct" >= 0 and "hero_attribute_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attributes_per_damage" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attributes_per_damage" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attributes_per_damage_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attributes_per_damage_check" check ("hero_attributes_per_damage"::text not in ('NaN','Infinity','-Infinity') and "hero_attributes_per_damage" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_rebirth_attribute_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_rebirth_attribute_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_rebirth_attribute_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_rebirth_attribute_bonus_pct_check" check ("hero_rebirth_attribute_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_rebirth_attribute_bonus_pct" >= 0 and "hero_rebirth_attribute_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_armor_reduction_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_armor_reduction_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_armor_reduction_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_armor_reduction_pct_check" check ("hero_attack_armor_reduction_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_armor_reduction_pct" >= 0 and "hero_attack_armor_reduction_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "hero_critical_chance_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_critical_chance_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_critical_chance_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_critical_chance_pct_check" check ("hero_critical_chance_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_critical_chance_pct" >= 0 and "hero_critical_chance_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "hero_attack_speed_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_speed_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_speed_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_speed_bonus_pct_check" check ("hero_attack_speed_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_speed_bonus_pct" >= 0 and "hero_attack_speed_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_interval_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_interval_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_interval_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_interval_reduction_check" check ("hero_attack_interval_reduction"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_interval_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_damage_bonus_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_damage_bonus_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_bonus_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_bonus_flat_check" check ("hero_damage_bonus_flat"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_bonus_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_initial_health" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_initial_health" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_initial_health_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_initial_health_check" check ("hero_initial_health"::text not in ('NaN','Infinity','-Infinity') and "hero_initial_health" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_health_regen_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_health_regen_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_health_regen_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_health_regen_per_second_check" check ("hero_health_regen_per_second"::text not in ('NaN','Infinity','-Infinity') and "hero_health_regen_per_second" >= 0 and "hero_health_regen_per_second" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_initial_armor" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_initial_armor" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_initial_armor_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_initial_armor_check" check ("hero_initial_armor"::text not in ('NaN','Infinity','-Infinity') and "hero_initial_armor" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attack_attribute_efficiency_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_attribute_efficiency_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_attribute_efficiency_pct_chec";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_attribute_efficiency_pct_chec" check ("hero_attack_attribute_efficiency_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_attribute_efficiency_pct" >= 0 and "hero_attack_attribute_efficiency_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_range" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_range" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_range_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_range_check" check ("hero_attack_range"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_range" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_damage_wood_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_damage_wood_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_wood_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_wood_flat_check" check ("hero_damage_wood_flat"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_wood_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_damage_gold_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_damage_gold_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_gold_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_gold_flat_check" check ("hero_damage_gold_flat"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_gold_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attack_gold_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_gold_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_gold_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_gold_flat_check" check ("hero_attack_gold_flat"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_gold_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_attack_wood_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_wood_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_wood_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_wood_flat_check" check ("hero_attack_wood_flat"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_wood_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "hero_damage_wood_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_damage_wood_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_damage_wood_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_damage_wood_bonus_pct_check" check ("hero_damage_wood_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "hero_damage_wood_bonus_pct" >= 0 and "hero_damage_wood_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "hero_attack_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_per_second_check" check ("hero_attack_per_second"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_attack_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_flat_check" check ("tower_attack_flat"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_health_regen_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_health_regen_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_health_regen_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_health_regen_per_second_check" check ("tower_health_regen_per_second"::text not in ('NaN','Infinity','-Infinity') and "tower_health_regen_per_second" >= 0 and "tower_health_regen_per_second" <= 10000);
alter table public.player_gameplay_stats add column if not exists "tower_attack_interval_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_interval_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_interval_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_interval_reduction_check" check ("tower_attack_interval_reduction"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_interval_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_critical_damage_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_critical_damage_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_critical_damage_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_critical_damage_bonus_pct_check" check ("tower_critical_damage_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "tower_critical_damage_bonus_pct" >= 0 and "tower_critical_damage_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "tower_damage_attack_growth" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_damage_attack_growth" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_damage_attack_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_damage_attack_growth_check" check ("tower_damage_attack_growth"::text not in ('NaN','Infinity','-Infinity') and "tower_damage_attack_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_basic_attack_growth" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_basic_attack_growth" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_basic_attack_growth_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_basic_attack_growth_check" check ("tower_basic_attack_growth"::text not in ('NaN','Infinity','-Infinity') and "tower_basic_attack_growth" >= 0);
alter table public.player_gameplay_stats add column if not exists "tower_attack_range" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_range" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_range_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_range_check" check ("tower_attack_range"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_range" >= 0);
alter table public.player_gameplay_stats add column if not exists "gold_mine_yield_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_yield_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_yield_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_yield_bonus_pct_check" check ("gold_mine_yield_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_yield_bonus_pct" >= 0 and "gold_mine_yield_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "gold_mine_yield_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_yield_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_yield_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_yield_flat_check" check ("gold_mine_yield_flat"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_yield_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "gold_mine_final_output_flat" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_final_output_flat" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_final_output_flat_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_final_output_flat_check" check ("gold_mine_final_output_flat"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_final_output_flat" >= 0);
alter table public.player_gameplay_stats add column if not exists "gold_mine_income_interval_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_income_interval_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_income_interval_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_income_interval_reduction_check" check ("gold_mine_income_interval_reduction"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_income_interval_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "gold_mine_build_cap" bigint not null default 0;
alter table public.player_gameplay_stats alter column "gold_mine_build_cap" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_gold_mine_build_cap_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_gold_mine_build_cap_check" check ("gold_mine_build_cap"::text not in ('NaN','Infinity','-Infinity') and "gold_mine_build_cap" >= 0 and "gold_mine_build_cap"=trunc("gold_mine_build_cap"));
alter table public.player_gameplay_stats add column if not exists "training_room_income_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "training_room_income_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_training_room_income_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_training_room_income_bonus_pct_check" check ("training_room_income_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "training_room_income_bonus_pct" >= 0 and "training_room_income_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "farmer_cap" bigint not null default 0;
alter table public.player_gameplay_stats alter column "farmer_cap" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_farmer_cap_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_farmer_cap_check" check ("farmer_cap"::text not in ('NaN','Infinity','-Infinity') and "farmer_cap" >= 0 and "farmer_cap"=trunc("farmer_cap"));
alter table public.player_gameplay_stats add column if not exists "faith_settlement_bonus" numeric not null default 0;
alter table public.player_gameplay_stats alter column "faith_settlement_bonus" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_faith_settlement_bonus_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_faith_settlement_bonus_check" check ("faith_settlement_bonus"::text not in ('NaN','Infinity','-Infinity') and "faith_settlement_bonus" >= 0);
alter table public.player_gameplay_stats add column if not exists "item_pool_size_reduction" bigint not null default 0;
alter table public.player_gameplay_stats alter column "item_pool_size_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_item_pool_size_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_item_pool_size_reduction_check" check ("item_pool_size_reduction"::text not in ('NaN','Infinity','-Infinity') and "item_pool_size_reduction" >= 0 and "item_pool_size_reduction"=trunc("item_pool_size_reduction"));
alter table public.player_gameplay_stats add column if not exists "weapon_upgrade_requirement_reduction" bigint not null default 0;
alter table public.player_gameplay_stats alter column "weapon_upgrade_requirement_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_weapon_upgrade_requirement_reduction_chec";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_weapon_upgrade_requirement_reduction_chec" check ("weapon_upgrade_requirement_reduction"::text not in ('NaN','Infinity','-Infinity') and "weapon_upgrade_requirement_reduction" >= 0 and "weapon_upgrade_requirement_reduction"=trunc("weapon_upgrade_requirement_reduction"));
alter table public.player_gameplay_stats add column if not exists "technology_cost_refund_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "technology_cost_refund_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_technology_cost_refund_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_technology_cost_refund_pct_check" check ("technology_cost_refund_pct"::text not in ('NaN','Infinity','-Infinity') and "technology_cost_refund_pct" >= 0 and "technology_cost_refund_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "technology_wood_cost_refund_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "technology_wood_cost_refund_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_technology_wood_cost_refund_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_technology_wood_cost_refund_pct_check" check ("technology_wood_cost_refund_pct"::text not in ('NaN','Infinity','-Infinity') and "technology_wood_cost_refund_pct" >= 0 and "technology_wood_cost_refund_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "technology_gold_cost_refund_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "technology_gold_cost_refund_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_technology_gold_cost_refund_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_technology_gold_cost_refund_pct_check" check ("technology_gold_cost_refund_pct"::text not in ('NaN','Infinity','-Infinity') and "technology_gold_cost_refund_pct" >= 0 and "technology_gold_cost_refund_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "lumberjack_efficiency" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_efficiency" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_efficiency_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_efficiency_check" check ("lumberjack_efficiency"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_efficiency" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_attack_interval_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_attack_interval_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_attack_interval_reduction_chec";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_attack_interval_reduction_chec" check ("lumberjack_attack_interval_reduction"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_attack_interval_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_attack_range" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_attack_range" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_attack_range_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_attack_range_check" check ("lumberjack_attack_range"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_attack_range" >= 0);
alter table public.player_gameplay_stats add column if not exists "lumberjack_harvest_yield_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_harvest_yield_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_harvest_yield_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_harvest_yield_bonus_pct_check" check ("lumberjack_harvest_yield_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_harvest_yield_bonus_pct" >= 0 and "lumberjack_harvest_yield_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "lumberjack_critical_chance_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_critical_chance_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_critical_chance_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_critical_chance_pct_check" check ("lumberjack_critical_chance_pct"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_critical_chance_pct" >= 0 and "lumberjack_critical_chance_pct" <= 100);
alter table public.player_gameplay_stats add column if not exists "lumberjack_critical_yield_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "lumberjack_critical_yield_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_lumberjack_critical_yield_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_lumberjack_critical_yield_bonus_pct_check" check ("lumberjack_critical_yield_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "lumberjack_critical_yield_bonus_pct" >= 0 and "lumberjack_critical_yield_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "wall_armor_per_second" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_armor_per_second" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_armor_per_second_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_armor_per_second_check" check ("wall_armor_per_second"::text not in ('NaN','Infinity','-Infinity') and "wall_armor_per_second" >= 0);
alter table public.player_gameplay_stats add column if not exists "global_final_damage_bonus_pct" numeric not null default 0;
alter table public.player_gameplay_stats alter column "global_final_damage_bonus_pct" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_global_final_damage_bonus_pct_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_global_final_damage_bonus_pct_check" check ("global_final_damage_bonus_pct"::text not in ('NaN','Infinity','-Infinity') and "global_final_damage_bonus_pct" >= 0 and "global_final_damage_bonus_pct" <= 10000);
alter table public.player_gameplay_stats add column if not exists "global_attack_armor_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "global_attack_armor_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_global_attack_armor_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_global_attack_armor_reduction_check" check ("global_attack_armor_reduction"::text not in ('NaN','Infinity','-Infinity') and "global_attack_armor_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "team_hero_wall_armor_bonus" numeric not null default 0;
alter table public.player_gameplay_stats alter column "team_hero_wall_armor_bonus" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_team_hero_wall_armor_bonus_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_team_hero_wall_armor_bonus_check" check ("team_hero_wall_armor_bonus"::text not in ('NaN','Infinity','-Infinity') and "team_hero_wall_armor_bonus" >= 0);
alter table public.player_gameplay_stats add column if not exists "enemy_initial_armor_reduction" numeric not null default 0;
alter table public.player_gameplay_stats alter column "enemy_initial_armor_reduction" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_enemy_initial_armor_reduction_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_enemy_initial_armor_reduction_check" check ("enemy_initial_armor_reduction"::text not in ('NaN','Infinity','-Infinity') and "enemy_initial_armor_reduction" >= 0);
alter table public.player_gameplay_stats add column if not exists "wall_wave_boss_stun_seconds" numeric not null default 0;
alter table public.player_gameplay_stats alter column "wall_wave_boss_stun_seconds" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_wall_wave_boss_stun_seconds_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_wall_wave_boss_stun_seconds_check" check ("wall_wave_boss_stun_seconds"::text not in ('NaN','Infinity','-Infinity') and "wall_wave_boss_stun_seconds" >= 0 and "wall_wave_boss_stun_seconds" <= 10);
alter table public.player_gameplay_stats add column if not exists "hero_attack_pct_per_minute" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attack_pct_per_minute" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attack_pct_per_minute_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attack_pct_per_minute_check" check ("hero_attack_pct_per_minute"::text not in ('NaN','Infinity','-Infinity') and "hero_attack_pct_per_minute" >= 0 and "hero_attack_pct_per_minute" <= 100);
alter table public.player_gameplay_stats add column if not exists "tower_attack_pct_per_minute" numeric not null default 0;
alter table public.player_gameplay_stats alter column "tower_attack_pct_per_minute" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_tower_attack_pct_per_minute_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_tower_attack_pct_per_minute_check" check ("tower_attack_pct_per_minute"::text not in ('NaN','Infinity','-Infinity') and "tower_attack_pct_per_minute" >= 0 and "tower_attack_pct_per_minute" <= 100);
alter table public.player_gameplay_stats add column if not exists "hero_attributes_pct_per_minute" numeric not null default 0;
alter table public.player_gameplay_stats alter column "hero_attributes_pct_per_minute" set default 0;
alter table public.player_gameplay_stats drop constraint if exists "player_gameplay_stats_hero_attributes_pct_per_minute_check";
alter table public.player_gameplay_stats add constraint "player_gameplay_stats_hero_attributes_pct_per_minute_check" check ("hero_attributes_pct_per_minute"::text not in ('NaN','Infinity','-Infinity') and "hero_attributes_pct_per_minute" >= 0 and "hero_attributes_pct_per_minute" <= 100);
commit;
